# Generated by Django 2.1.4 on 2019-05-15 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190514_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_picture',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 18, 24, 18, 67095), verbose_name='date published'),
        ),
    ]
